# @package _global_

defaults:
  - _self_
  - datamodule: sign.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - callbacks: null

  - experiment: sign.yaml


datamodule:
  batch_size: 12

model:
  save_path: ${hydra:runtime.output_dir}


task_name: "eval"


tags: ["dev"]




# passing checkpoint path is necessary for evaluation
ckpt_path: /root/sign_diffuse/logs/train/runs/2022-11-02_20-59-32/checkpoints/last.ckpt
